server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zaalima
    username: postgres
    password: Siy@123uikey

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true